server:
  servlet:
    context-path: /data-service

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: data-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        deregister: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
        health-check-path: /data-service/actuator/health
        health-check-interval: 10s
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5445}/${DATABASE_NAME:data-service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345678}
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service-svc:8080/auth-service/oauth2/jwks
      client:
        registration:
          api-communication:
            scope: read
            provider: api-communication-provider
            client-secret: 'dkl8UIp8HcCNvnj2F90/OXLtRc/vFlzVYT7rXu04iTg='
            authorization-grant-type: client_credentials
            client-id: api-communication
        provider:
          api-communication-provider:
            token-uri: http://auth-service-svc:8080/auth-service/oauth2/token

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread])
      %yellow(%logger{15}) - %msg%n}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
  endpoint:
    health:
      show-details: always

redis:
  host: redis
  port: 6379
  password: a4rT44Rce32w87htRft56
  socketTimeout: 400
  commandTimeout: 600
  database: 0
  
project:
  kafka:
    kafka-address-with-port: kafka:9092
    group-id: microservice-sample-data-service
    enable-consumer: true
    enable-producer: true
    retry:
      backoff:
        ms: 100000
    producer:
      bootstrap-servers: kafka:9092
      retries: 0
      order-match-topic:
        name: project-producer-order-match-topic
      topic:
        name: project-global-topic
        replica: 1
        auto-create-topics: true
    producer-topic:
      partition-count: 1
    consumer:
      bootstrap-servers: kafka:9092
      group-id: microservice-sample-data-service-group
      auto-offset-reset: earliest
      order-match-topic:
        name: project-consumer-order-match-topic
      topic:
        name: data-service-topic
        partition-count: 2
        replica: 1
        auto-create-topics: true